baseurl = "https://m45t3r.github.io/"
title = "Random thoughts"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Thiago Kenji Okada"
googleAnalytics = "UA-54080516-1"

[Author]
    name = "Thiago Kenji Okada"
    profile = "https://github.com/m45t3r"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Random thoughts"
    description = "dd if=/dev/random of=/dev/brain"
    github = "https://github.com/m45t3r"
    linkedin = "https://www.linkedin.com/in/thiago-kenji-okada-65357933/"
    stackoverflow = "https://stackoverflow.com/users/2751730/m45t3r"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About me"
    url = "/page/about/"
    weight = 2
